apiVersion: v1
kind: Pod
metadata:
  name: nginx
  #namespace: preprod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /mnt/gfs
      name: nginx-logs
  volumes:
  - name: nginx-logs
    glusterfs:
      path: prod
      endpoints: gluster-service
      readOnly: false
